language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
      
install:
    - pip install -r requirements.txt

services:
    - postgresql

before_script:
    - psql -c 'create database sleep_test;' -U postgres
    - psql -c "create user test_user with password 'test';" -U postgres
      #    - psql -c 'create database travis_ci_test;' -U postgres

addons:
    postgresql: "9.5"

script: python -m pytest
