language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
      
install:
    - pip install -r requirements.txt

services:
    - postgresql

before_script:
    - psql -c "CREATE DATABASE sleep_test;" -U postgres
    - psql -c "DROP TABLE IF EXISTS slt_night CASCADE;" -U postgres
    - psql -c "CREATE TABLE slt_night (
                night_id SERIAL UNIQUE,
                start_date date NOT NULL,
                start_time time NOT NULL,
                PRIMARY KEY (night_id)
              );" -U postgres
    - psql -c "DROP TABLE IF EXISTS slt_nap;" -U postgres
    - psql -c "CREATE TABLE slt_nap (
                nap_id SERIAL UNIQUE, 
                start_time time NOT NULL,
                duration interval NOT NULL,
                night_id integer NOT NULL,
                PRIMARY KEY (nap_id),
                FOREIGN KEY (night_id) REFERENCES slt_night (night_id)
              );" -U postgres
    - psql -c "create user test_user with password 'test';" -U postgres
      #    - psql -c 'create database travis_ci_test;' -U postgres

addons:
    postgresql: "9.5"

script: python -m pytest
